### ISSUE TITLE
Microphone doesn’t work

### ISSUE THREAD

**Issue by fbruetting** [flathub/com.wire.WireDesktop#16]
I now took a first call since long time and recognized that my microphones don’t work. I can select them in the application settings, but I don’t see action at the VU meter of my microphones, when I make any noise – whereas in the web application of web.wire.com, I see the bar jumping around and everything works there. I first thought that the microphone access right is missing, but the Gnome settings 3.32 shows in the Wire app settings, that Wire has access to whole /dev.

What surprises me, is that the webcam worked and sent video. Can you reproduce or do you have any idea about what happens here?

**Comment by x80486** [comment]
I guess it must be something with your setup – although it's weird. I've seen similar issues with the camera, etc. in the Wire's Issue tracker. I use the video feature from time to time and so far I haven't had any issues.

This is a screenshot of a microphone test:

![image](https://user-images.githubusercontent.com/34633617/55296326-a6a5a300-53e5-11e9-9a83-8f2bf0647bcb.png)

Would you mind trying the `AppImage` (if possible) and see if you get the same result?

**Comment by x80486** [comment]
@fbruetting, do you still have the same issue?

**Comment by x80486** [comment]
Hey @fbruetting, I'm going to close this one. I still believe this is not an issue with the Flatpak, but if anything, with the software itself.

You can reopen it if you find out that it's affecting the Flatpak package only.

**Comment by fbruetting** [comment]
Sorry, I don’t use NSA-Wire anymore…
