### ISSUE TITLE
Zoomed-in icon under KDE Plasma (X+Wayland)

### ISSUE THREAD

**Issue by mielouk** [flathub/com.wire.WireDesktop#19]
A while ago I had conflicting icons from an earlier installed AppImage of Wire which interfered with each other and resulted in no icon at all being displayed. Either via alt+tab or in the task bar, the icon was not visible. This could be fixed with deleting the old AppImage icon from a location in the homefolder, which I don't remember.  

This problem on the other hand seems to be different. 
On my Cinnamon Arch install (the one mentioned above) the icon looks like this, as it should.

![Bildschirmfoto vom 2019-05-02 17-36-41](https://user-images.githubusercontent.com/3057062/57088394-7d3ca780-6d02-11e9-90cb-333cd233c950.png)

In my KDE Plasma session the icon looks like this, both, under X and Wayland. 
![Wire 2019-05-02 at 17 47 16](https://user-images.githubusercontent.com/3057062/57088714-2aafbb00-6d03-11e9-800a-df8fb41f5a3f.png)

**Comment by x80486** [comment]
There are a couple of issues around the same subject in the Wire's issue tracker. Make sure they are fixed; some other folk(s) reported something like that a while ago.

Again, the AppImage should yield the same result(s).

**Comment by mielouk** [comment]
So it is not flatpak related. I'll take this somewhere else. Thx anyway!
