### ISSUE TITLE
Unable to type ` and similar characters with Fcitx

### ISSUE THREAD

**Issue by Mikaela** [flathub/com.wire.WireDesktop#20]
Workaround: `flatpak override --user --talk-name=org.freedesktop.portal.Fcitx com.wire.WireDesktop`

Upstream: https://github.com/flatpak/flatpak/issues/2031 / https://gitlab.com/fcitx/fcitx/issues/429

**Comment by x80486** [comment]
I'll add it by default, although a little bit hesitant (due to the nature of this application) because of the wider permission than what the default portal one offers. I'll follow the issue in GitLab and when merged I'll remove this one.

**Comment by Mikaela** [comment]
Would that cause tis to break again for some users until their distributions updated Fcitx (or Flatpak)?

**Comment by x80486** [comment]
Since the fix should go into the Fcitx's input method framework, I guess you are right, this would stay here for a while...so don't panic, I won't remove it then! :sunglasses:
