### ISSUE TITLE
Why does Wire run with `--no-sandbox` ?

### ISSUE THREAD

**Issue by Mikaela** [flathub/com.wire.WireDesktop#21]
I was testing if `flatpak run com.wire.WireDesktop --startup` is the method for starting Wire in the background and looked into `htop` to see how it affects my memory usage and happened to notice that Wire gets parameter `--no-sandbox` and I started wondering why? Is Flatpak so well sandboxed that it's unnecessary to have sandboxing in Wire? I think the permissions already look a bit wide.

https://github.com/flathub/com.wire.WireDesktop/blob/258bf19d07942e0e68f3e459e2d66c42654ca974/com.wire.WireDesktop.json#L12-L24

![Screenshot from 2019-05-24 08-26-47](https://user-images.githubusercontent.com/831184/58309767-9d88ef00-7df4-11e9-8cf6-eae43442e781.png)

**Comment by Mikaela** [comment]
This appears to come from Wire upstream.

**Comment by TingPing** [comment]
Also the Chrome sandbox can't run inside Flatpak anyway.

**Comment by fermulator** [comment]
Why did this get closed? (the question has not been answered) - #2507 is not related

**Comment by TingPing** [comment]
It is impossible to run the current Chromium sandbox inside of Flatpak. So the upstream answer doesn't even matter anyway.

**Comment by Mikaela** [comment]
> It is impossible to run the current Chromium sandbox inside of Flatpak. 

Why? Is there an issue about that somewhere? Is Flatpak sandbox more secure than the Chromium one, does it render the Chromium one unrequired?

**Comment by TingPing** [comment]
The namespace API is considered insecure so its part of the syscall blacklist.

Chromium would have to be ported to use `flatpak-spawn`.

No the situation is not more secure.
