### ISSUE TITLE
KDE Global menu permissions

### ISSUE THREAD

**Issue by alexjp** [flathub/com.wire.WireDesktop#3]
Flatpak has changed to require the permissions for global menu on kde.

Relevant issue: https://github.com/flatpak/flatpak/issues/2012

It seems to need the "--talk-name=com.canonical.AppMenu.Registrar".

Could you guys rebuild it with that permission request ?

Thanks

**Comment by x80486** [comment]
Hi @alexjp, I've never use KDE before.

I can install KDE on a Fedora VM that I have, but I would need more information on what should be fixed/changed. Moreover, if you do `flatpak run --talk-name=com.canonical.AppMenu.Registrar com.wire.WireDesktop`, does that fixes what you are facing?

**Comment by alexjp** [comment]
Yes, that does fix it.

You can see this comment specificly in the issue i refereced before why it is needed ( now, it wasn't at 0.11.7 of flatpak ) : https://github.com/flatpak/flatpak/issues/2012#issuecomment-416187860

Also you can see the solution that kdeapps did, their diff: https://cgit.kde.org/flatpak-kde-applications.git/commit/?id=0ccbc716568441922961a8ae372284a9d07be882

**Comment by TingPing** [comment]
Flatpak reverted its change to runtimes to not allow permissions, so I think either this just needs to be re-added to runtime (if its safe) or if its already there this just needs rebuilt.

**Comment by alexjp** [comment]
> Flatpak reverted its change to runtimes to not allow permissions, so I think either this just needs to be re-added to runtime (if its safe) or if its already there this just needs rebuilt.

Thanks TingPing ... didn't knew that it was reverted.
In my system, it does need that command line option to have the global menu ( without it, it doesn't appear ).
I am using flatpak 1.0.6, could that be the problem ?

**Comment by x80486** [comment]
Based on [this](https://github.com/flatpak/flatpak/blob/master/NEWS/) file they were reverted in version `1.0.4`.

Something I don't fully understand is if `--talk-name=com.canonical.AppMenu.Registrar` would be present by default on KDE runtimes and not on Freedesktop ones.

Moreover, I don't think rebuilding the artifact would make any difference, right? It was released yesterday itself. So @TingPing, based on that, what would be your recommendation? Is it OK to just add the `--talk-name=com.canonical.AppMenu.Registrar` to this manifest?

**Comment by x80486** [comment]
All right! Thanks...I will just update the manifest with that setting and KDE folks can have their **Global Menu**.
