### ISSUE TITLE
Failed to open file + Failed to load included manifest

### ISSUE THREAD

**Issue by gimmelovn** [flathub/com.wire.WireDesktop#49]
# PLEASE REMOVE THIS PROJECT IF IT NO LONGER IS ACTIVELY SUPPORTED

# INSTALLATION DESCRIPTION
RHEL9 Workstation (fresh). Following your instructions, I received the following errors (below) after 2 failed attempts. As a workaround, I installed the Wire desktop app directly from Flathub who currently offers the Wire app from their website that works on RHEL9 >> https://flathub.org/apps/details/com.wire.WireDesktop

# FIRST ATTEMPT AS INSTRUCTIONS ARE GIVEN
[root@localhost com.wire.WireDesktop]# flatpak-builder build --force-clean --install-deps-from=flathub --install --user com.wire.WireDesktop.yml
Can't load 'com.wire.WireDesktop.yml': Failed to open file “/home/Downloads/com.wire.WireDesktop/com.wire.WireDesktop.yml”: No such file or directory
[root@localhost com.wire.WireDesktop]#

# SECOND ATTEMPT AFTER YAML CORRECTION
[root@localhost com.wire.WireDesktop]# flatpak-builder build --force-clean --install-deps-from=flathub --install --user com.wire.WireDesktop.yaml

(flatpak-builder:55099): flatpak-builder-ERROR **: 09:12:50.700: Failed to load included manifest (/home/Downloads/com.wire.WireDesktop/shared-modules/libsecret/libsecret.json): Failed to open file “/home/Downloads/com.wire.WireDesktop/shared-modules/libsecret/libsecret.json”: No such file or directory
Trace/breakpoint trap (core dumped)
[root@localhost com.wire.WireDesktop]#

**Comment by x80486** [comment]
This repository is generally updated after every official release from `Wire Desktop`.

To solve your issue you would need to understand how [`Git` sub-modules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) work — `libsecret` is managed in such way.

If you are unable to install `Wire Desktop` from `Flathub`, feel free to open an issue here with the details, but the instructions from this repository's `README` are intended for developers.
